# Generated by Django 3.2.5 on 2022-03-15 19:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(help_text='Enter a Cat Breed (e.g. Shirazi)', max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Breed names should contain at least 2 letters.')]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='nickname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Cat names should contain at least 2 letters.')]),
        ),
    ]
